### ISSUE TITLE
re-throw unhandled errors

### ISSUE THREAD

**Issue by chrisguttandin** [cartant/rxjs-interop#7]
Hi Nicholas,

what do you think about re-throwing errors which do not have an error handler instead of swallowing them?

I noticed that if the user doesn't provide an error handler the noop function gets used instead.
https://github.com/cartant/rxjs-interop/blob/main/source/to-observer.ts#L25
https://github.com/cartant/rxjs-interop/blob/main/source/to-observer.ts#L31

I would suggest to default to something like `(err) => { throw err }` instead to avoid swallowing errors. If a user really wants to ignore errors they could still provide a noop function themselves.

**Comment by cartant** [comment]
Yeah, that would be much better. Should be fixed in 1.0.3.

**Comment by cartant** [comment]
I suppose this is a breaking change, but all bug fixes are breaking changes, so ... no major version bump.

**Comment by chrisguttandin** [comment]
Yes, I think it's fine to release it as a patch if we consider the old behavior to be a bug.

Thanks a lot for the quick fix.
