### ISSUE TITLE
update Subscribable type for RxJS v7

### ISSUE THREAD

**Issue by chrisguttandin** [cartant/rxjs-interop#8]
In RxJS v7 the definition of the `Subscribable` type was reduced to only accept a partial observer.

https://github.com/ReactiveX/rxjs/commit/2d600c75c1065d862a2089dc1cd26007996b1c9d#diff-e780718ac92bd7fc85acbc37236743d7c42082aabbc02e673979c70e02f43471L89-R90

https://github.com/ReactiveX/rxjs/commit/8c13e0a3dbd88cc473677cd41c9f09cc26a3d947#diff-e780718ac92bd7fc85acbc37236743d7c42082aabbc02e673979c70e02f43471L89-L91

These changes make the `Subscribable` from rxjs-interop incompatible with RxJS v7.

**Comment by cartant** [comment]
Finally got around to looking at this. It's closed by https://github.com/cartant/rxjs-interop/commit/0e8cee00cc2afd7e3b5411709e8f62d7267479b1 and the publication of 2.0.0.

**Comment by chrisguttandin** [comment]
Thanks a lot for the update.
